/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlarmChart: typeof import('./components/charts/AlarmChart.vue')['default']
    AlarmList: typeof import('./components/charts/AlarmList.vue')['default']
    AlarmNotification: typeof import('./components/AlarmNotification.vue')['default']
    DataCard: typeof import('./components/DataCard.vue')['default']
    DeviceStatus: typeof import('./components/charts/DeviceStatus.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FullScreenButton: typeof import('./components/FullScreenButton.vue')['default']
    MapChart: typeof import('./components/charts/MapChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenAdapter: typeof import('./components/ScreenAdapter.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
    TemperatureChart: typeof import('./components/charts/TemperatureChart.vue')['default']
  }
}
